http:
  port: 8080
  # uncomment for production
  # port: 80
admin:
  port: 9876
  hostname: localhost
  # uncomment for production
  # hostname: 104.41.59.129
apiEndpoints:
  ideas:
    host: localhost
    # uncomment for production
    # host: 104.41.59.129
    paths: 
     - '/ideas'
     - '/votes'
  users:
    host: localhost
    # uncomment for production
    # host: 104.41.59.129    
    paths: 
     - '/users'
     - '/users/register'
     - '/users/login'
     - '/users/me'
     - '/users/user'
serviceEndpoints:
  httpbin:
    url: 'http://localhost:8888'
  httpbin2:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  ideas:
    apiEndpoints:
      - ideas
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  users:
    apiEndpoints:
      - users
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin2
              changeOrigin: true